name: Deploy actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  init:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: diplom
        ports:
          - 3306
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install composer dependencies
      - run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Install npm dependencies
      - run: npm install
      - name: Copy .env
      - run: composer run post-root-package-install
      - name: Generate key
      - run: composer run post-create-project-cmd
      - name: Set "diplom" database in var DB_DATABASE
      - env:
          DB_DATABASE: diplom


